# define parameters depending for the php version installed
# for any new version, only specify keys with values different from defaults
# defaults should work for php > 7.3
defaults:
  php_dir: "/etc/php/{{ php_ver }}"
  php_bin: "php-fpm{{ php_ver }}"
  php_pkg_apcu: "php{{ php_ver }}-apcu"
  php_pkg_spe:
    - "php{{ php_ver }}-bcmath"
    - "php{{ php_ver }}-gmp"
    - "php{{ php_ver }}-imagick"
    - "php{{ php_ver }}-mbstring"
    - "php{{ php_ver }}-redis"
    - "php{{ php_ver }}-xml"
    - "php{{ php_ver }}-zip"
  php_socket: "/run/php/php{{ php_ver }}-fpm.sock"

"7.3":
  php_pkg_apcu: "php-apcu"
  php_pkg_spe:
    - "php-imap"
    - "php-imagick"
    - "php-redis"
    - "php7.3-xml"
    - "php7.3-zip"
    - "php7.3-mbstring"

"7.2":
  php_pkg_apcu: "php-apcu"
  php_pkg_spe:
    - "php-imap"
    - "php-imagick"
    - "php-redis"
    - "php7.2-xml"
    - "php7.2-zip"
    - "php7.2-mbstring"

"7.0":
  php_pkg_apcu: "php-apcu"
  php_pkg_spe:
    - "php-imap"
    - "php-imagick"
    - "php-redis"
    - "php7.0-mcrypt"
    - "php7.0-xml"
    - "php7.0-zip"
    - "php7.0-mbstring"

"5":
  php_dir: "/etc/php5"
  php_bin: "php5-fpm"
  php_pkg_apcu: "php5-apcu"
  php_pkg_spe:
    - "php5-imap"
    - "php5-imagick"
    - "php5-redis"
    - "php5-mcrypt"
