---
# handlers file for nextcloud
- name: restart mysql
  ansible.builtin.service:
    name: "{{ mysql_daemon }}"
    state: restarted

- name: start http
  ansible.builtin.service:
    name: "{{ nextcloud_websrv }}"
    state: started

- name: restart http
  ansible.builtin.service:
    name: "{{ nextcloud_websrv }}"
    state: restarted

- name: reload http
  ansible.builtin.service:
    name: "{{ nextcloud_websrv }}"
    state: reloaded

- name: start php-fpm
  ansible.builtin.service:
    name: php{{ php_ver }}-fpm
    state: started

- name: reload php-fpm
  ansible.builtin.service:
    name: php{{ php_ver }}-fpm
    state: reloaded

- name: start redis
  ansible.builtin.service:
    name: redis-server
    state: started

- name: restart redis
  ansible.builtin.service:
    name: redis-server
    state: restarted
